"""Status labels for embedding components authored for transfer only."""

IMPLEMENTATION_STATUS_LABELS = (
    "PROVISIONAL_SMOKE_ONLY",
    "FILE_ARTIFACT_SOURCE",
    "ENGINEERING_VALIDATION",
    "NOT_FOR_FINAL_THESIS_CONCLUSIONS",
    "IMPLEMENTED_NOT_EXECUTED",
    "TRANSFER_PENDING_VALIDATION",
)

__all__ = ["IMPLEMENTATION_STATUS_LABELS"]
